# Scope parameter constants and configurations

# Channel-type parameters that use CHANNEL(n) instead of AXIS(n)
CHANNEL_PARAMETERS = [
    "AIN", "AINBI", "AOUT",
    "DV_CONTROLWORD", "DV_IN", "DV_OUT", "DV_STATUSWORD",
    "IN", "OUT",
]

# Axis-type parameters
AXIS_PARAMETERS = [
    "ACCEL", "ACCEL_FACTOR", "ADDAX_AXIS", "AFF_GAIN", "ATYPE",
    "AXIS_A_OUTPUT", "AXIS_ACCEL", "AXIS_B_OUTPUT", "AXIS_BLENDING",
    "AXIS_D_OUTPUT", "AXIS_DEBUG_A", "AXIS_DEBUG_B", "AXIS_DEBUG_C",
    "AXIS_DEBUG_D", "AXIS_DECEL", "AXIS_DIRECTION", "AXIS_DPOS",
    "AXIS_ENABLE", "AXIS_ENABLE_OVERRIDE", "AXIS_ERROR_COUNT",
    "AXIS_FASTDEC", "AXIS_FS_LIMIT", "AXIS_MAX_ACC", "AXIS_MAX_JERK",
    "AXIS_MAX_JOG_ACC", "AXIS_MAX_JOG_SPEED", "AXIS_MAX_SPEED",
    "AXIS_MAX_TORQUE", "AXIS_MODE", "AXIS_RS_LIMIT", "AXIS_SPEED",
    "AXIS_UNITS", "AXIS_Z_OUTPUT", "AXISSTATUS",
    "BACKLASH_DIST", "CHANGE_DIR_LAST", "CLOSE_WIN", "CLOSE_WINB",
    "CLUTCH_RATE", "CORNER_FACTOR", "CORNER_MODE", "CORNER_RADIUS",
    "CORNER_STATE", "CREEP",
    "D_GAIN", "D_ZONE_MAX", "D_ZONE_MIN", "DAC", "DAC_OUT", "DAC_SCALE",
    "DATUM_IN", "DECEL", "DECEL_ANGLE", "DEMAND_EDGES", "DEMAND_SPEED",
    "DEMAND_SPEED_NORMALISED",
    "DISTANCE_TO_SYNC", "DPOS",
    "DRIVE_BRAKE_OUTPUT", "DRIVE_CONTROL", "DRIVE_CONTROLWORD",
    "DRIVE_CURRENT", "DRIVE_CW_MODE", "DRIVE_ENABLE", "DRIVE_FE",
    "DRIVE_FE_LIMIT", "DRIVE_INDEX", "DRIVE_INPUTS", "DRIVE_MODE",
    "DRIVE_MONITOR", "DRIVE_NEG_TORQUE", "DRIVE_PARAMETER",
    "DRIVE_POS_TORQUE", "DRIVE_PROFILE", "DRIVE_REP_DIST",
    "DRIVE_SET_VAL", "DRIVE_STATUS", "DRIVE_TORQUE", "DRIVE_TYPE",
    "DRIVE_VALUE", "DRIVE_VELOCITY",
    "ENCODER", "ENCODER_BITS", "ENCODER_CONTROL", "ENCODER_FILTER",
    "ENCODER_ID", "ENCODER_STATUS", "ENCODER_TURNS",
    "END_DIR_LAST", "END_VELOCITY", "ENDMOVE", "ENDMOVE_BUFFER",
    "ENDMOVE_SPEED",
    "FAST_JOG", "FASTDEC", "FASTJERK", "FE", "FE_LATCH", "FE_LIMIT",
    "FE_LIMIT_MODE", "FE_RANGE", "FEED_OVERRIDE", "FHOLD_IN", "FHSPEED",
    "FORCE_ACCEL", "FORCE_DECEL", "FORCE_DWELL", "FORCE_JERK",
    "FORCE_RAMP", "FORCE_SPEED", "FRAME_REP_DIST", "FRAME_SCALE",
    "FS_LIMIT", "FULL_SP_RADIUS", "FWD_IN", "FWD_JOG", "FWD_START",
    "I_GAIN", "IDLE", "IN_POS", "IN_POS_DIST", "IN_POS_SPEED",
    "INTERP_FACTOR", "INVERT_STEP", "JERK", "JERK_FACTOR", "JOGSPEED",
    "LINK_AXIS", "LOADED", "LOOKAHEAD_FACTOR",
    "MARK", "MARKB", "MERGE", "MICROSTEP", "MOVE_COUNT", "MOVE_COUNT_INC",
    "MOVE_ENDMOVE_SPEED", "MOVE_FORCE_ACCEL", "MOVE_FORCE_DECEL",
    "MOVE_FORCE_RAMP", "MOVE_FORCE_SPEED", "MOVE_PA", "MOVE_PA_CONT",
    "MOVE_PA_IDLE", "MOVE_PB", "MOVE_PB_CONT", "MOVE_PB_IDLE",
    "MOVE_STARTMOVE_SPEED", "MOVELINK_MODIFY", "MOVES_BUFFERED",
    "MPOS", "MSPEED", "MSPEED_FILTER", "MSPEEDF", "MTYPE",
    "NEG_OFFSET", "NTYPE",
    "OFFPOS", "OPEN_WIN", "OPEN_WINB", "OUTLIMIT", "OV_GAIN",
    "P_GAIN", "POS_DELAY", "POS_OFFSET", "POSI_SEQ_DELAY",
    "POSI_SEQ_MODE", "PP_STEP", "PS_ENCODER", "PWM_CYCLE", "PWM_MARK",
    "RAISE_ANGLE", "REG_INPUTS", "REG_POS", "REG_POSB",
    "REGIST_CONTROL", "REGIST_DELAY", "REGIST_SPEED", "REGIST_SPEEDB",
    "REMAIN", "REMAIN_TIME", "REP_DIST", "REP_OPTION", "REV_IN",
    "REV_JOG", "REV_START",
    "ROBOT_DPOS", "ROBOT_FE", "ROBOT_FE_LATCH", "ROBOT_FE_LIMIT",
    "ROBOT_FE_RANGE", "ROBOT_FS_LIMIT", "ROBOT_RS_LIMIT",
    "ROBOT_SP_MODE", "ROBOT_UNITS", "ROBOTSTATUS", "RS_LIMIT",
    "S_REF", "S_REF_OUT", "SERVO", "SPEED", "SPEED_FACTOR", "SPEED_SIGN",
    "SRAMP", "START_DIR_LAST", "STARTMOVE_SPEED", "STOP_ANGLE",
    "STOPPING_DISTANCE", "SYNC_AXIS", "SYNC_CONTROL", "SYNC_DPOS",
    "SYNC_DWELL", "SYNC_FLIGHT", "SYNC_PAUSE", "SYNC_TIME",
    "SYNC_TIMER", "SYNC_WITHDRAW",
    "T_REF", "T_REF_OUT", "TABLE_POINTER", "TANG_DIRECTION",
    "TCP_DPOS", "TCP_FS_LIMIT", "TCP_RS_LIMIT", "TCP_UNITS",
    "TRIOPCTESTVARIAB",
    "UNITS",
    "V_LIMIT", "VECTOR_BUFFERED", "VERIFY", "VFF_GAIN",
    "VP_ACCEL", "VP_DEMAND_ACCEL", "VP_DEMAND_DECEL", "VP_DEMAND_JERK",
    "VP_DEMAND_SPEED", "VP_ERROR", "VP_JERK", "VP_MODE", "VP_OPTIONS",
    "VP_POSITION", "VP_SPEED",
    "WORLD_ACCEL", "WORLD_DECEL", "WORLD_DPOS", "WORLD_FASTDEC",
    "WORLD_FS_LIMIT", "WORLD_JERK", "WORLD_JOGSPEED", "WORLD_RS_LIMIT",
    "WORLD_SPEED", "WORLD_UNITS",
]

SCOPE_PARAMETERS = AXIS_PARAMETERS + CHANNEL_PARAMETERS

# Set for fast lookup of channel-type parameters
CHANNEL_PARAMETERS_SET = set(CHANNEL_PARAMETERS)

# Virtual (computed) parameters: map display name → underlying Trio SCOPE parameter.
# These are not real controller parameters; their data is derived post-capture.
_VIRTUAL_PARAM_MAP = {
    "DEMAND_SPEED_NORMALISED": "DEMAND_SPEED",  # units/servocycle → units/second
}

# Maximum axis index supported on Trio controllers (MC664 supports 128 axes 0..127;
# extended / virtual axes can go up to 255).
MAX_CONTROLLER_AXIS = 255

